version: "3.4"

  # host process
services:
  inshakerparser:
    image: ${DOCKER_REGISTRY-}inshakerparser
    build:
      context: .
      dockerfile: OxfordParser/Dockerfile
    depends_on:
      - rabbitmq
      - mongo
    networks:
      - app_network

  # scalable worker
  worker:
    image: ${DOCKER_REGISTRY-}worker
    build:
      context: .
      dockerfile: RabbitMQConsumer/Dockerfile
    depends_on:
      - rabbitmq
      - mongo
    networks:
      - app_network
  # RabbitMQ bus
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - app_network

  # MongoDB
  mongo:
    image: mongo
    container_name: "mongo"
    restart: always
    ports:
      - 27018:27017
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - app_network

  # MongoExpress GUI
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
